"""baseline

Revision ID: 2fe3e291e473
Revises: 
Create Date: 2026-08-28 19:43:16.225375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe3e291e473'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bans',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('customs',
    sa.Column('custom_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('format', sa.String(length=4), nullable=False),
    sa.Column('duration_h', sa.Integer(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('map_pool', sa.Text(), nullable=False),
    sa.Column('draft_mode', sa.String(length=16), nullable=False),
    sa.Column('captain_method', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('start_asap', sa.Boolean(), nullable=False),
    sa.Column('vc_category', sa.Integer(), nullable=True),
    sa.Column('reg_channel', sa.Integer(), nullable=True),
    sa.Column('reg_message', sa.Integer(), nullable=True),
    sa.Column('vc_a', sa.Integer(), nullable=True),
    sa.Column('vc_b', sa.Integer(), nullable=True),
    sa.Column('config_chan', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("format IN ('BO1','BO3','BO5')", name='ck_custom_fmt'),
    sa.PrimaryKeyConstraint('custom_id')
    )
    op.create_table('draft_picks',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('pick_no', sa.Integer(), nullable=False),
    sa.Column('team_side', sa.String(length=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('match_id', 'pick_no')
    )
    op.create_table('drafts',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('turn_side', sa.String(length=1), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('guilds',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('map_veto',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('team_side', sa.String(length=1), nullable=True),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('match_id', 'step')
    )
    op.create_table('maps',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('competitive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'name')
    )
    op.create_table('match_map_sides',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_index', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.Column('team_side', sa.String(length=1), nullable=False),
    sa.Column('choice', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('match_id', 'map_index')
    )
    op.create_table('match_players',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=1), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.Column('is_sub', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('match_id', 'user_id')
    )
    op.create_table('match_results',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('map_index', sa.Integer(), nullable=False),
    sa.Column('map_name', sa.String(length=32), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('winner_side', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('match_id', 'map_index')
    )
    op.create_table('match_teams',
    sa.Column('team_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=1), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('custom_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=4), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('party_code', sa.String(length=16), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_pick_side', sa.String(length=1), nullable=True),
    sa.Column('side_map', sa.String(length=32), nullable=True),
    sa.Column('side_pick', sa.String(length=8), nullable=True),
    sa.Column('side_pick_side', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('member_roles',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.CheckConstraint("role IN ('superadmin','admin','player')", name='ck_member_role'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'role')
    )
    op.create_table('panel_boards',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("tier IN ('player','admin','superadmin')", name='ck_panel_tier'),
    sa.PrimaryKeyConstraint('guild_id', 'tier')
    )
    op.create_table('player_stats',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('mvps', sa.Integer(), nullable=False),
    sa.Column('captain_wins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'season_id', 'user_id')
    )
    op.create_table('queues',
    sa.Column('queue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('custom_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=4), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('riot_id', sa.String(length=32), nullable=True),
    sa.Column('riot_puuid', sa.String(length=64), nullable=True),
    sa.Column('riot_region', sa.String(length=8), nullable=True),
    sa.Column('riot_status', sa.String(length=16), nullable=True),
    sa.Column('riot_reviewed_by', sa.Integer(), nullable=True),
    sa.Column('riot_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rank_updated_at', sa.DateTime(), nullable=True),
    sa.Column('main_role', sa.String(length=16), nullable=True),
    sa.Column('roles_json', sa.Text(), nullable=False),
    sa.Column('cur_rank', sa.String(length=16), nullable=True),
    sa.Column('peak_rank', sa.String(length=16), nullable=True),
    sa.Column('cur_rr', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("main_role IS NULL OR main_role IN ('Duelist','Controller','Initiator','Sentinel','Flex')", name='ck_user_role'),
    sa.CheckConstraint("riot_status IS NULL OR riot_status IN ('pending','approved','denied')", name='ck_user_riot_status'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('custom_registrations',
    sa.Column('custom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reg_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_id'], ['customs.custom_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('custom_id', 'user_id')
    )
    op.create_table('queue_members',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.queue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queue_members')
    op.drop_table('custom_registrations')
    op.drop_table('users')
    op.drop_table('queues')
    op.drop_table('player_stats')
    op.drop_table('panel_boards')
    op.drop_table('member_roles')
    op.drop_table('matches')
    op.drop_table('match_teams')
    op.drop_table('match_results')
    op.drop_table('match_players')
    op.drop_table('match_map_sides')
    op.drop_table('maps')
    op.drop_table('map_veto')
    op.drop_table('guilds')
    op.drop_table('drafts')
    op.drop_table('draft_picks')
    op.drop_table('customs')
    op.drop_table('bans')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
