"""add foreign keys

Revision ID: 988263c5152c
Revises: 2fe3e291e473
Create Date: 2026-08-28 19:47:45.266730

Adds the ForeignKey constraints that were missing despite `PRAGMA
foreign_keys=ON` being set on every connection (bot/db/engine.py) — most
tables referencing another row weren't actually enforced.

Deliberately NOT touched here, hand-pruned out of the autogenerate diff:
  - `guild_id` / `user_id` columns: NOT ForeignKeys, on purpose — see the
    docstrings on Guild/User in bot/db/models.py (both rows are created
    lazily, well after other tables already reference that id).
  - `Match.custom_id`: NOT a ForeignKey, on purpose — deleting a custom never
    touches its match history (see bot/db/models.py's Match.custom_id
    comment).
  - `match_spectators` (unrelated, unused legacy table), a handful of
    autogenerated `NOT NULL` tightenings, a `CHECK` constraint autogenerate
    wanted to add to `users`, and dropping `users.elo` (a legacy column no
    longer in the model) — all unrelated to foreign keys and each a separate
    decision with its own data-safety questions; left for their own migration
    if wanted.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '988263c5152c'
down_revision: Union[str, Sequence[str], None] = '2fe3e291e473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# (table, fk_name, local_col, target_table, target_col, ondelete)
_FKS = [
    ("customs", "fk_customs_match_id_matches", "match_id", "matches", "match_id", None),
    ("draft_picks", "fk_draft_picks_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("drafts", "fk_drafts_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("map_veto", "fk_map_veto_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("match_map_sides", "fk_match_map_sides_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("match_players", "fk_match_players_team_id_match_teams", "team_id", "match_teams", "team_id", None),
    ("match_players", "fk_match_players_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("match_results", "fk_match_results_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("match_teams", "fk_match_teams_match_id_matches", "match_id", "matches", "match_id", "CASCADE"),
    ("queues", "fk_queues_custom_id_customs", "custom_id", "customs", "custom_id", "CASCADE"),
]


def upgrade() -> None:
    for table, name, col, target_table, target_col, ondelete in _FKS:
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.create_foreign_key(
                name, target_table, [col], [target_col], ondelete=ondelete
            )


def downgrade() -> None:
    for table, name, col, target_table, target_col, ondelete in reversed(_FKS):
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.drop_constraint(name, type_="foreignkey")
